version: "3"

services:
 web:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "3000:3000"
  volumes:
   - .:/app
   - /app/node_modules
  command: sh -c "sleep 10 && npm run dev"
  networks:
   - test_project
  depends_on:
   - db
 db:
  image: postgres:latest
  restart: always
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: 1234
   POSTGRES_DB: postgres
  ports:
   - "5432:5432"
  networks:
   - test_project
  volumes:
   - mydata:/var/lib/postgresql/data

volumes:
 mydata: {}

networks:
 test_project:
